name: BedWars
main: BedWars\BedWars
version: 1.0.5
api: 2.0.0
load: STARTUP
author: LewBr
description: BedWars MiniGame
website: www.twitter.com/PocketGamesPE
commands:
 bw:
  description: "BedWars!"
  usage: "/bw"
  permission: bw.tp
 bwvote:
  description: "Vote para comecar"
  usage: "/bwvote"
  permission: bw.vote
 bwstart:
  description: "Comece o jogo"
  usage: "/bwstart"
  permission: bw.start
 bwstop:
  description: "Pare o jogo"
  usage: "/bwstop"
  permission: bw.stop
permissions:
 bw:
  default: false
  description: "-"
  children:
   bw.tp:
    default: true
    description: "Todos teleportar para o jogo"
   bw.vote:
    default: true
    description: "Permitir votar no jogo"
   bw.start:
    default: op
    description: "Permitir comecar o jogo agora"
   bw.stop:
    default: op
    description: "Permitir parar o jogo"
