name: BedWars
main: BedWars\BedWars
version: 1.0.5
api: 2.0.0
load: STARTUP
author: Tarik02
description: BedWars MiniGame
commands:
 bw:
  description: "BedWars!"
  usage: "/bw"
  permission: bw.tp
 bwvote:
  description: "Vote to start"
  usage: "/bwvote"
  permission: bw.vote
 bwstart:
  description: "Start game"
  usage: "/bwstart"
  permission: bw.start
 bwstop:
  description: "Stop game"
  usage: "/bwstop"
  permission: bw.stop
permissions:
 bw:
  default: false
  description: "-"
  children:
   bw.tp:
    default: true
    description: "Enable teleporting to a game"
   bw.vote:
    default: true
    description: "Enable game voting"
   bw.start:
    default: op
    description: "Enable Force game start"
   bw.stop:
    default: op
    description: "Enable game stop"
